version: 2

models:
  - name: fact_grades
    description: "One record per grading event for courses, subsections, and problems"
    columns:
      - name: emission_time
        description: "Timestamp, to the second, of when this event was emitted"
        data_type: DateTime64(3)
      - name: org
        data_type: String
      - name: course_key
        data_type: String
      - name: course_name
        data_type: String
      - name: course_run
        data_type: String
      - name: entity_id
        description: "The block ID or course key for the graded entity"
        data_type: String
      - name: entity_name
        data_type: String
      - name: entity_name_with_location
        data_type: Nullable(String)
      - name: grade_type
        description: "The type of object graded"
        tests:
          - accepted_values:
              values: ["course", "subsection", "problem"]
        data_type: Nullable(String)
      - name: actor_id
        data_type: String
      - name: scaled_score
        description: "A ratio between 0 and 1, inclusive, of the learner's grade"
        data_type: Float32
      - name: grade_bucket
        description: "A displayable value of grades sorted into 10% buckets. Useful for grouping grades together to show high-level learner performance"
        data_type: String
