version: 2

models:

  - name: user_pii
    description: "The user PII table for reports."
    columns:
      - name: user_id
        data_type: String
        description: "The user id"
      - name: external_user_id
        data_type: String
        description: "The external user id"
      - name: username
        data_type: String
        description: "The username of the user"
      - name: name
        data_type: String
        description: "The name of the user"
      - name: email
        data_type: String
        description: "The email of the user"

  - name: dim_user_pii
    description: "A denormalized table of user PII information"
    columns:
      - name: external_user_id
        data_type: String
        description: "The external user id"
      - name: username
        data_type: String
        description: "The username"
      - name: name
        data_type: String
        description: "The name of the user"
      - name: email
        data_type: String
        description: "The email of the user"

  - name: dim_at_risk_learners
    description: "A record for each learner determined to be at risk of dropping out of a given course"
    columns:
      - name: org
        data_type: String
        description: "The organization that the course belongs to"
      - name: course_key
        data_type: String
        description: "The course key for the course"
      - name: course_name
        data_type: String
        description: "The name of the course"
      - name: course_run
        data_type: String
        description: "The course run for the course"
      - name: actor_id
        data_type: string
        description: "The xAPI actor identifier"
      - name: username
        data_type: string
        description: "The username of the user"
      - name: name
        data_type: string
        description: "The name of the user"
      - name: email
        data_type: string
        description: "The email of the user"
      - name: enrollment_mode
        data_type: string
        description: "The mode of enrollment"
      - name: course_grade
        data_type: float64
        description: "The most recent grade for the learner"
      - name: enrolled_at
        data_type: DateTime
        description: "The timestamp, to the second, of the most recent enrollment action for this learner and course."
      - name: last_visited
        data_type: datetime
        description: "The last time the learner visited a page for this course"
