version: 2

models:
  - name: fact_enrollments
    description: "A record for each enrollment event"
    columns:
      - name: emission_time
        description: "Timestamp, to the second, of when this event was emitted"
      - name: org
      - name: course_name
      - name: run_name
      - name: actor_id
      - name: enrollment_mode
        description: ""
      - name: enrollment_status
        description: "Whether a learner is actively enrolled in a course"
        tests:
          - accepted_values:
              values: ["registered", "unregistered"]
