version: 2

sources:
  - name: xapi
    database: "{{ env_var('XAPI_SCHEMA', 'xapi') }}"
    description: "the xapi database in clickhouse"
    tables:
      - name: xapi_events_all_parsed
        identifier: "{{ env_var('ASPECTS_XAPI_TABLE', 'xapi_events_all_parsed') }}"
        description: "Materialized view of parsed xapi events"
        columns:
          - name: event_id
          - name: verb_id
          - name: actor_id
          - name: org
          - name: course_id
          - name: emission_time
            description: "timestamp of when the event was emitted"
          - name: event_str
            description: "json string of the event"

      - name: enrollment_events
        identifier: "{{ env_var('ASPECTS_ENROLLMENT_EVENTS_TABLE', 'enrollment_events') }}"
        description: "Materialized view of enrollment events"
        columns:
          - name: event_id
          - name: emission_time
          - name: actor_id
          - name: object_id
          - name: course_key
          - name: org
          - name: verb_id
          - name: enrollment_mode

      - name: video_playback_events
        identifier: "{{ env_var('ASPECTS_VIDEO_PLAYBACK_EVENTS_TABLE', 'video_playback_events') }}"
        columns:
          - name: event_id
          - name: emission_time
          - name: actor_id
          - name: object_id
          - name: course_key
          - name: org
          - name: verb_id
          - name: video_position

      - name: problem_events
        identifier: "{{ env_var('ASPECTS_PROBLEM_EVENTS_TABLE', 'problem_events') }}"
        columns:
          - name: event_id
          - name: emission_time
          - name: actor_id
          - name: object_id
          - name: course_key
          - name: org
          - name: verb_id
          - name: responses
          - name: scaled_score
          - name: success
          - name: interaction_type
          - name: attempts

      - name: navigation_events
        identifier: "{{ env_var('ASPECTS_NAVIGATION_EVENTS_TABLE', 'navigation_events') }}"
        columns:
          - name: event_id
          - name: emission_time
          - name: actor_id
          - name: object_id
          - name: course_key
          - name: org
          - name: verb_id
          - name: object_type
          - name: starting_position
          - name: ending_point

      - name: grading_events
        identifier: "{{ env_var('ASPECTS_GRADING_EVENTS_TABLE', 'grading_events') }}"
        columns:
          - name: event_id
          - name: emission_time
          - name: actor_id
          - name: object_id
          - name: course_key
          - name: org
          - name: verb_id
          - name: scaled_score
      
      - name: completions_events
        identifier: "{{ env_var('ASPECTS_COMPLETION_EVENTS_TABLE', 'completion_events') }}"
        columns:
          - name: event_id
          - name: emission_time
          - name: actor_id
          - name: object_id
          - name: course_key
          - name: org
          - name: verb_id
          - name: progress_percent

      - name: forum_events
        identifier: "{{ env_var('ASPECTS_FORUM_EVENTS_TABLE', 'forum_events') }}"
        columns:
          - name: event_id
          - name: emission_time
          - name: org
          - name: course_key
          - name: actor_id
          - name: object_id
          - name: verb_id

  - name: event_sink
    database: "{{ env_var('ASPECTS_EVENT_SINK_DATABASE', 'event_sink')}}"
    tables:
      - name: course_block_names
        columns:
          - name: location
          - name: block_name
          - name: course_key

      - name: course_names
        columns:
          - name: course_key
          - name: course_name
          - name: course_run
          - name: org
