version: 2

sources:
  - name: xapi
    database: "{{ env_var('ASPECTS_XAPI_DATABASE', 'xapi') }}"
    description: "the xapi database in clickhouse"
    tables:
      - name: xapi_events_all
        identifier: "{{ env_var('ASPECTS_VECTOR_RAW_XAPI_TABLE', 'xapi_events_all') }}"
        description: "Base table for raw xAPI events"
        columns:
          - name: event_id
          - name: emission_time
          - name: event

  - name: event_sink
    database: "{{ env_var('ASPECTS_EVENT_SINK_DATABASE', 'event_sink')}}"
    tables:

      - name: course_blocks
        columns:
          - name: org
          - name: course_key
          - name: location
          - name: display_name
          - name: xblock_data_json
          - name: order
          - name: edited_on
          - name: dump_id
          - name: time_last_dumped

      - name: course_overviews
        columns:
          - name: org
          - name: course_key
          - name: display_name
          - name: course_start
          - name: course_end
          - name: enrollment_start
          - name: enrollment_end
          - name: self_paced
          - name: course_data_json
          - name: created
          - name: modified
          - name: dump_id
          - name: time_last_dumped

      - name: user_profile
        columns:
          - name: id
          - name: user_id
          - name: name
          - name: email
          - name: meta
          - name: courseware
          - name: language
          - name: location
          - name: year_of_birth
          - name: gender
          - name: level_of_education
          - name: mailing_address
          - name: city
          - name: country
          - name: state
          - name: goals
          - name: bio
          - name: profile_image_uploaded_at
          - name: phone_number
          - name: dump_id
          - name: time_last_dumped

      - name: external_id
        columns:
          - name: external_user_id
          - name: external_id_type
          - name: username
          - name: user_id
          - name: dump_id
          - name: time_last_dumped
