
version: 2

models:
  - name: xapi_video_events
    description: "All xAPI video statements with the common fields parsed to the top level"
    columns:
      - name: event_id
        description: "The unique key for this statement"
        tests:
          - unique
          - not_null

sources:
  - name: xapi_raw
    schema: xapi
    tables:
      - name: xapi_events_all_parsed
