# Build documentation for dbt-aspects on every PR to main.
# Deploy documentation to gh-pages branch on every push to main.

name: Build documentation

on:
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./.github/
  CLICKHOUSE_DB: "xapi"
  CLICKHOUSE_USER: "ch_admin"
  CLICKHOUSE_PASSWORD: "ch_password"

jobs:
  build:
    name: Deploy dbt docs to github pages
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.x"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          dbt deps
      - name: Run Clickhouse
        run: |
          docker compose up -d
      - name: Build docs
        run: |
          dbt docs generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          publish_dir: ./target
          commit_message: "docs: update docs for "
